### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mozack** [milaboratory/mitcr#1]
Hi,

The website: http://mitcr.milaboratory.com/ appears to be down.

Thanks,
Lisle

**Comment by mikessh** [comment]
Hello!

Working fine for me, have you checked it at http://www.downforeveryoneorjustme.com ?

**Comment by dbolotin** [comment]
@mozack, thanks for letting us know! In this and next week some problems might arise with our sites, as we are moving them to new infrastructure.
