### ISSUE TITLE
Galaxy wrapper?

### ISSUE THREAD

**Issue by dpryan79** [milaboratory/mitcr#3]
I don't suppose you'd be interested in writing a Galaxy wrapper for this? We have some groups using this (via bioinformaticians) and it'd be nice to just let the wet lab folks directly use this in Galaxy :) I'd also be happy to write a Galaxy wrapper if you're not interested or won't have time to quickly put one together.

**Comment by dbolotin** [comment]
Hi,

unfortunately, we don't support MiTCR anymore, and switched development to [MiXCR](https://github.com/milaboratory/mixcr). So, we don't have plans to develop MiTCR plugin for Galaxy.

Of course, if you think it will simplify life for local wet lab folks, you can write Galaxy plugin. But in general, I would not recommend using MiTCR for new projects. Last version of MiTCR is way behind from MiXCR in terms of selectivity/specificity and functionality.

Also, thank you for the idea! We will think about implementation of Galaxy plugin for MiXCR.

**Comment by dpryan79** [comment]
Thanks, I noticed MiXCR after posting the issue and agree completely that that's the better way forward. Please feel encouraged to write the Galaxy wrapper for MiXCR instead :)
