### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by Acetylcholine88** [milaboratory/mitcr#4]
Hey! I am super new to this here (and to most programming)
Can someone help me how to install the software on my mac? Ideally an explanation for computer dummies, I have no experience with using the terminal etc. (I am already glad if one can provide me with a simple explanation/information source for this though!)

Thanks - very much appreciated!

**Comment by dbolotin** [comment]
Hi,

first of all, we recommend using our new tool called [MiXCR](https://github.com/milaboratory/mixcr). It has superior specificity, selectivity and functionality compared to MiTCR (please see [original paper](https://doi.org/10.1038/nmeth.3364) on MiXCR).

Working with terminal is very easy, you can easily educate yourself, there are tons of materials on the net. You can start with this video:
https://www.youtube.com/watch?v=-Vl4rpZVA6I

There are two videos dedicated to MiXCR data analysis (thanks to [nextgenerationsequencinghq](https://www.youtube.com/channel/UChWRKseeSiroQiAbJcuBLZA) YouTube channel):

  * [Part 1](https://www.youtube.com/watch?v=0g9Xt6sQNVU)
  * [Part 2](https://www.youtube.com/watch?v=bIGUVeBIgKU)

The only suggestion is to ignore the installation way proposed in the video and use [brew](https://brew.sh/) for this task. It is as easy as copy-pasting and executing the following two commands:

* Install Brew itself:
    ```
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ```
* Install MiXCR using brew:
    ```
    brew install milaboratory/all/mixcr
    ```

**Comment by Acetylcholine88** [comment]
Hi!

That was very helpful, especially the videos.
Nonetheless, I get this error when I am trying to install homebrew
Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/lib

I set up a new root password but it still won’t work and I was kicked out after trying to use the root password (3 failed attempts).
So what can I do?

Thank you!


On Feb 19, 2017, at 4:12 PM, Dmitry Bolotin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

first of all, we recommend using our new tool called MiXCR<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_milaboratory_mixcr&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=PmsIcArgy66w37mQSxwl9uz3fURf2-2DoaKZndKEujE&e=>. It has superior specificity, selectivity and functionality compared to MiTCR (please see original paper<https://urldefense.proofpoint.com/v2/url?u=https-3A__doi.org_10.1038_nmeth.3364&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=Ko5lMXWyHQmdA1cjOC7E3MTwkLX25uy32x57Vr_jGPA&e=> on MiXCR).

Working with terminal is very easy, you should educate yourself, there are tons of materials on the net. You can start with this video:
https://www.youtube.com/watch?v=-Vl4rpZVA6I<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_watch-3Fv-3D-2DVl4rpZVA6I&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=wLL9OpF-KMgo_-R21if_YQMjyvo5VSP4aNHdJWpobcc&e=>

There are two videos dedicated to MiXCR data analysis (thanks to nextgenerationsequencinghq<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_channel_UChWRKseeSiroQiAbJcuBLZA&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=oBk2_h8qHI72eFR_jYJOVlpRYvJf8FgwlXqJTuY6M60&e=> YouTube channel):

  *   Part 1<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_watch-3Fv-3D0g9Xt6sQNVU&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=z7W_FswJggrzL1kS6WhbdaoFtd4rifrp9z8ABakm1Kk&e=>
  *   Part 2<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_watch-3Fv-3DbIGUVeBIgKU&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=JINkoPL3KLwFxTXQZ8sLmroIzZ1ob1QYXtgxOxi2xxo&e=>

The only suggestion is to ignore the installation way proposed in the video and use brew<https://urldefense.proofpoint.com/v2/url?u=https-3A__brew.sh_&d=DwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=IvLcdSR-3lYG80BCc-aPlqxnq9O30atdQl6B4oY1HqA&m=r-GfjXrtYMTl_cb9o5xwI4Mk-sKSINl8mSpiywNvgW8&s=-6LEALrvWbHzGlgplWVDTWtxCnnj1_f_M0v1ocfr4os&e=> for this task. It is as easy as copy-pasting and executing the following two commands:

  *   Install Brew itself:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


  *   Install MiXCR using brew:

brew install milaboratory/all/mixcr

**Comment by mikessh** [comment]
Hello,

It seems to be an issue related to the homebrew installation on your PC, not a bug in the MIXCR software. You should contact the IT department of your university for this kind of support instead of using this issues section.
